[[redirects]]
from = "/"
to = "/index.html"

[[redirects]]
from = "/.netlify/functions/index"
to = "/index.html"

[[redirects]]
from = "/index"
to = "/index.html"

[[redirects]]
from = "/contact"
to = "/contact.html"

[[redirects]]
from = "/.netlify/functions/index/contact"
to = "/contact.html"

[[redirects]]
from = "/acercade"
to = "/acercade.html"

[[redirects]]
from = "/.netlify/functions/index/acercade"
to = "/acercade.html"
